# Generated by Django 4.1.5 on 2023-04-22 18:37

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGroup',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('build_year', models.DateField(verbose_name='Build Year')),
                ('build_material', models.CharField(choices=[('Estera', 'Estera'), ('Concreto', 'Concreto'), ('Madera', 'Madera')], max_length=100)),
                ('family_code', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Family ID')),
                ('members', models.ManyToManyField(to='identify.account')),
            ],
            options={
                'verbose_name': 'Hogar',
                'verbose_name_plural': 'Hogares',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('safe_zone', models.CharField(max_length=255, verbose_name='Safe Zone')),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='picture')),
                ('home_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='home.homegroup')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
                'ordering': ['number'],
            },
        ),
    ]
