# Generated by Django 4.1.5 on 2023-04-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegroup',
            name='build_year',
            field=models.CharField(max_length=4, verbose_name='Build Year'),
        ),
    ]
