# Generated by Django 4.1.5 on 2023-04-22 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=45, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=9, verbose_name='Phone Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('gender', models.CharField(choices=[('Masculino', 'Male'), ('Femenino', 'Female')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('dni',), name='unique_dni'),
        ),
    ]
