# Generated by Django 4.1.5 on 2023-04-22 18:37

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon')),
                ('type', models.CharField(choices=[('food', 'Food'), ('health', 'Health')], max_length=100, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ElementItem',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True, verbose_name='Date Added')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name='Date Expiration')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last Update')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='backpack.element')),
            ],
            options={
                'verbose_name': 'Elemento Item',
                'verbose_name_plural': 'Elementos Items',
                'ordering': ['-date_added'],
            },
        ),
    ]
